export { default as Profile } from './Profile/Profile'
export { default as About } from './About/About'
export { default as Achievement } from './Achievement/Achievement'
export { default as Skills } from './Skills/Skills'
export { default as Contact } from './Contact/Contact'
